import Navbar from "../../components/Navbar";
import { ThemeProvider } from "../../context/ThemeContext";
import ThemeToggle from "../../components/ToggleTheme";
import AuthProvider from "../../context/AuthContex";
import './globals.css'
import SecondaryNav from "../../components/SecondaryNav";
import Breadcrumb from "../../components/Breadcrumb";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ThemeProvider>
            <Navbar />
            <SecondaryNav />
            <Breadcrumb />
            {children}
            <ThemeToggle />
          </ThemeProvider>
        </AuthProvider>
        
      </body>
    </html>
  );
}
