import Navbar from "../../components/Navbar";
import { ThemeProvider } from "../../context/ThemeContext";
import ThemeToggle from "../../components/ToggleTheme";
import './globals.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Navbar />
          {children}
          <ThemeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
}
