import Navbar from "../../components/Navbar";
import { ThemeProvider } from "../../context/ThemeContext";
import ThemeToggle from "../../components/ToggleTheme";
import AuthProvider from "../../context/AuthContex";
import './globals.css'
import SecondaryNav from "../../components/SecondaryNav";
import Breadcrumb from "../../components/Breadcrumb";
import { CartProvider } from "../../context/CartContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ThemeProvider>
            <CartProvider>
              <Navbar />
              <SecondaryNav />
              <Breadcrumb />
              {children}
              <ThemeToggle />
            </CartProvider>
          </ThemeProvider>
        </AuthProvider>
        
      </body>
    </html>
  );
}
